version: "3.9"

services:
  frontend:
    build: ./frontend
    ports:
      - "3001:5173"
    environment:
      - VITE_API_URL=http://localhost:3000/api/
    working_dir: /app
    command: npm run dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=postgres
      - JWT_SECRET=FBUEQIFU2837JFEHOUHGFUHUEC93038Y85430892M8CYGUROW
    working_dir: /app
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d:ro

    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
